name: Cron Job

on:
  # Triggers the workflow every 5 minutes
  schedule:
    - cron: "*/1 * * * *"

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./hoyolab-check-in.js
        with:
          milliseconds: 1000
