name: cronjob

# Triggers the workflow every 2:00 AM UTC
on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  auto-check-in:
    runs-on: ubuntu-latest
    env:
      LTOKEN: ${{ secrets.LTOKEN }}
      LTUID: ${{ secrets.LTUID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Execute check-in script
        run: node hoyolab-check-in.js
