name: Cron Job

on:
  push:

jobs:
  cron:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Check-in
        uses: ./.github/workflows/check-in.yml
