name: cronjob

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  auto-check-in:
    runs-on: ubuntu-latest
    env:
      LTOKEN: ${{ secrets.LTOKEN }}
      LTUID: ${{ secrets.LTUID }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: test env
        run: |
          echo $LTOKEN
          echo $LTUID

      - name: Execute check-in script
        run: node hoyolab-check-in.js
