name: cronjob

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  auto-check-in:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Execute hoyolab-check-in.js
        run: node hoyolab-check-in.js
